apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-{{ .Values.zone }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
      zone: {{ .Values.zone }}
  template:
    metadata:
      labels:
        app: nginx
        zone: {{ .Values.zone }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

